
service: badge-generator

frameworkVersion: '3'

provider:
  name: aws
  iam:
    role: arn:aws:iam::554279632216:role/getSteamInformationRole
  runtime: python3.7
  versionFunctions: false
  memorySize: 128
  region: us-east-1

functions:
  handler:
    handler: handler.lambda_handler  
    layers:
      - "arn:aws:lambda:us-east-1:554279632216:layer:python-app-dependencies:1"
    events: 
      - http: 
          path: badge
          method: post       

layers:
  python-app-dependencies:
    path: requests-layer
    compatibleRuntimes:
      - python3.7
    description: "Dependencies requests for python functions"