service: badge-generator

frameworkVersion: '3'

provider:
  name: aws
  iam:
    role: arn:aws:iam::554279632216:role/getSteamInformationRole
  runtime: python3.7
  versionFunctions: false
  memorySize: 128
  region: us-east-1

functions:
  handler:
    description: lambda that generate a steam badge
    handler: handler.lambda_handler 
    events: 
      - http: 
          path: badge
          method: post       
