name: Deploy steam badge 

on:
  push:
    branches:
      - main

jobs:
  development-deploy:
    name:  development-deploy
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14.x 
    strategy:
      matrix:
        python-version:
          - 3.7 
    steps:    
    - uses: actions/checkout@v2
    - name: Use python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }} 
    - run: pip install -t requests -r aws_requirements.txt  
    - run: python handler.py        
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: AKIAYCDND7VMMHMZKQPH
        AWS_SECRET_ACCESS_KEY: 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