name: Deploy steam badge 

on:
  push:
    branches:
      - main

jobs:
  development-deploy:
    name:  development-deploy
    runs-on: ubuntu-latest
    environment: 
      name: Development
    strategy:
      matrix:
        python: [3.7]
    steps:
    - uses: actions/checkout@v3
    - name: Use python ${{ matrix.python }}
      uses: actions/python@v3
      with:
        python-version: ${{ matrix.python }}
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}